name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip  # Enables built-in pip caching

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('doc_requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install Project Dependencies
        run: |
          pip install numpy  # Add your core dependencies here
          pip install -r requirements.txt  # If you have a requirements file
          pip install -e .  # Install your package in editable mode

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          
      - name: Install MkDocs Essentials
        run: |
          pip install -r doc_requirements.txt  # If you have a requirements file
          pip install mkdocs-material mkdocstrings[python]

      - name: Configure Environment
        run: |
          echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Build Documentation
        run: |
          mkdocs build --strict --no-strict

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
